# Database configuration
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_vault_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# API documentation configuration
springdoc:
  show-actuator: true
  packagesToScan: com.cryptovaultdoo.cryptovault
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: method
    path: /